backend:
  name: github
  repo: sinardunia/porto
  branch: master
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow

site_url: "https://waltahh.vercel.app"

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "post"
    label: "Posts"
    folder: "src/content/blog"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{slug}}"

    fields:
      - label: "ID"
        name: "id"
        widget: "string"
        required: false

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Slug"
        name: "slug"
        widget: "string"

      - label: "Excerpt"
        name: "excerpt"
        widget: "text"
        required: false

      - label: "Cover Image URL"
        name: "cover_image_url"
        widget: "string"
        required: false

      - label: "Cover Image Alt"
        name: "cover_image_alt"
        widget: "string"
        required: false

      - label: "Created At"
        name: "created_at"
        widget: "datetime"

      - label: "Updated At"
        name: "updated_at"
        widget: "datetime"
        required: false

      - label: "Published"
        name: "is_published"
        widget: "boolean"
        default: true

      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"